FileVersion = 1

[Project]
Name = "libbson-beef"
TargetType = "BeefLib"
StartupObject = "libbson_beef.Program"

[Configs.Debug.Win64]
OtherLinkFlags = "$(LinkFlags) ws2_32.lib"
BeefLibType = "Static"
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\bson_d.lib"]

[Configs.Release.Win64]
OtherLinkFlags = "$(LinkFlags) ws2_32.lib"
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\bson.lib"]
